### ISSUE TITLE
patch failed: config.yaml:17

### ISSUE THREAD

**Issue by ubdbra001** [RSE-Sheffield/fair4rs-lesson-setup#24]
Hi @tdjames1 

I tried following the instructions, got to applying the patch and received the following message:

```
error: CITATION.cff: already exists in index
error: patch failed: config.yaml:17
error: config.yaml: patch does not apply
```

I'm on windows and I started with the [Rmd template](https://github.com/carpentries/workbench-template-rmd) from the carpentries if that makes any difference.

Thanks,

Dan

**Comment by tdjames1** [comment]
Thanks for noting this error, it's because the carpentries template has been adjusted to include a `CITATION.cff` file which it didn't at the time of developing the patch file (see #23). A quick fix would be to remove lines 1-30 inclusive of the patch file, then edit the `CITATION.cff` with the info indicated in that section of the patch file.

**Comment by ubdbra001** [comment]
Got it, will give that a go and report back. Thanks!

**Comment by ubdbra001** [comment]
Had a go and that fixes the first part of the error:
```
error: CITATION.cff: already exists in index
```

The second part remained:
```
error: patch failed: config.yaml:17
error: config.yaml: patch does not apply
```

I had a bit of a tinker with it and it's because there's been a [change](https://github.com/carpentries/workbench-template-rmd/commit/3f304af52371c4e411af9664bd349354ad2e59c0) to `config.yaml` that means that patch doesn't match up any more. Once I added the additional text it worked okay.

Would it be worth me regenerating the patch given I'm going to have to make these changes to my repo anyway?

**Comment by tdjames1** [comment]
If you'd be happy to do it that would be great!

I create the patch by creating a repo from the workbench template, making the various changes then running:
``` 
git diff daa55ad6609e.. > fair4rs_config.patch
```
where the `daa55ad` commit was the initial commit i.e. the unmodified workbench template.
